uploads = []
outputs = []

[[generated]]
id = "B3dxihr7OHqwQtWAkPeB_"
uri = "file://artifacts/ecosort/public/trash/oil_bottle.png"
type = "image"
title = "generated_image"

[[generated]]
id = "pRr8D2oDf58q-AMQoQ5Sa"
uri = "file://artifacts/ecosort/public/trash/sauce_jar.png"
type = "image"
title = "generated_image"

[[generated]]
id = "TXNZb_GZgsk22d3fo83FW"
uri = "file://artifacts/ecosort/public/trash/detergent_bottle.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ja1bhvy4KcRSp_I_g4ps_"
uri = "file://artifacts/ecosort/public/trash/plastic_fork.png"
type = "image"
title = "generated_image"

[[generated]]
id = "o4AX6HMQ3qT7P8I113T5n"
uri = "file://artifacts/ecosort/public/trash/tuna_can.png"
type = "image"
title = "generated_image"

[[generated]]
id = "fBTCMPoSe7MEJ7GNsSZDg"
uri = "file://artifacts/ecosort/public/trash/face_mask.png"
type = "image"
title = "generated_image"

[[generated]]
id = "OnjY0YR946pBfrWh3ZBlc"
uri = "file://artifacts/ecosort/public/trash/cotton_swab.png"
type = "image"
title = "generated_image"

[[generated]]
id = "-5GXs6wh6LY1QnBiVlRp4"
uri = "file://artifacts/ecosort/public/trash/broken_headphones.png"
type = "image"
title = "generated_image"

[[generated]]
id = "LMHyLQgR7U-vyyP8_n5WK"
uri = "file://artifacts/ecosort/public/trash/cd_disc.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Abz31ghjBJlAV4vMi5YbN"
uri = "file://artifacts/ecosort/public/trash/dead_aa_batteries.png"
type = "image"
title = "generated_image"

[[generated]]
id = "5u0sHvTSlXh1odwbCSFpZ"
uri = "file://artifacts/ecosort/public/trash/vinegar_bottle.png"
type = "image"
title = "generated_image"

[[generated]]
id = "e1gVhY-kwNAWgmjOeb_OP"
uri = "file://artifacts/ecosort/public/trash/mayo_jar.png"
type = "image"
title = "generated_image"

[[generated]]
id = "VgevguEHAaCtCF6cQGsJc"
uri = "file://artifacts/ecosort/public/trash/sparkling_bottle.png"
type = "image"
title = "generated_image"

[[generated]]
id = "cViaLGeNuhl9w1Yd9QUV4"
uri = "file://artifacts/ecosort/public/trash/plastic_container.png"
type = "image"
title = "generated_image"

[[generated]]
id = "4xoLHfw5ppF_1tsQ7GGXh"
uri = "file://artifacts/ecosort/public/trash/plastic_straw.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Vh3qC6e6aK9bzhU78eohw"
uri = "file://artifacts/ecosort/public/trash/vhs_cassette.png"
type = "image"
title = "generated_image"

[[generated]]
id = "QszV5oBST0avgFXxRZP0P"
uri = "file://artifacts/ecosort/public/trash/eraser.png"
type = "image"
title = "generated_image"

[[generated]]
id = "rlEkm5DBPwenlXZdxCSkQ"
uri = "file://artifacts/ecosort/public/trash/broken_keyboard.png"
type = "image"
title = "generated_image"

[[generated]]
id = "GGMev3bVRlMlmzAEFnC3N"
uri = "file://artifacts/ecosort/public/trash/broken_remote.png"
type = "image"
title = "generated_image"

[[generated]]
id = "CpGfWOCTVVOATWlwUKmQ8"
uri = "file://artifacts/ecosort/public/trash/fluorescent_bulb.png"
type = "image"
title = "generated_image"

[[generated]]
id = "wlp3Dm6OyY-uX5ebllfnc"
uri = "file://artifacts/ecosort/public/trash/pasta_leftovers.png"
type = "image"
title = "generated_image"

[[generated]]
id = "jatPPOqYSkrhZsxopb3P_"
uri = "file://artifacts/ecosort/public/trash/wilted_flowers.png"
type = "image"
title = "generated_image"

[[generated]]
id = "NZlGFPwrXW8x1NemVR2EG"
uri = "file://artifacts/ecosort/public/trash/kiwi_peel.png"
type = "image"
title = "generated_image"

[[generated]]
id = "5OUSMRPuDUSIlBjNrIYsM"
uri = "file://artifacts/ecosort/public/trash/vegetable_scraps.png"
type = "image"
title = "generated_image"

[[generated]]
id = "RYQcFk-JtOPhgaLh6Aq3I"
uri = "file://artifacts/ecosort/public/trash/pizza_crust.png"
type = "image"
title = "generated_image"

[[generated]]
id = "mwknKBJFusAZUa6N4YIxi"
uri = "file://artifacts/ecosort/public/trash/onion_peel.png"
type = "image"
title = "generated_image"

[[generated]]
id = "_Qy6UpbXXIC_Z445RkcmR"
uri = "file://artifacts/ecosort/public/trash/tomato_scraps.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Fqyq54jsLAgXFsKP3tXsL"
uri = "file://artifacts/ecosort/public/trash/dry_leaves.png"
type = "image"
title = "generated_image"

[[generated]]
id = "KGZmqbOtc8773nluSg7MN"
uri = "file://artifacts/ecosort/public/trash/cherry_pits.png"
type = "image"
title = "generated_image"

[[generated]]
id = "pRuryMvDexC7Oec85qjnv"
uri = "file://artifacts/ecosort/public/trash/rice_leftovers.png"
type = "image"
title = "generated_image"

[[generated]]
id = "iYq0kSCJ4fLxU-du9hR9_"
uri = "file://artifacts/ecosort/public/trash/olive_jar.png"
type = "image"
title = "generated_image"

[[generated]]
id = "kRZ2hYYUQq4yUxk7ez50b"
uri = "file://artifacts/ecosort/public/trash/juice_bottle_glass.png"
type = "image"
title = "generated_image"

[[generated]]
id = "MS9BcEEa22cG1VNEhen4R"
uri = "file://artifacts/ecosort/public/trash/perfume_bottle.png"
type = "image"
title = "generated_image"

[[generated]]
id = "rr371oM50R-qEozMUOnHs"
uri = "file://artifacts/ecosort/public/trash/pesto_jar.png"
type = "image"
title = "generated_image"

[[generated]]
id = "vhD_sQfkur6kwn_dhlCP6"
uri = "file://artifacts/ecosort/public/trash/grappa_bottle.png"
type = "image"
title = "generated_image"

[[generated]]
id = "3LrIT54J_uqsB2y1yZX9a"
uri = "file://artifacts/ecosort/public/trash/liquor_bottle.png"
type = "image"
title = "generated_image"

[[generated]]
id = "69WwtUJ8SChmPlWUfzxv_"
uri = "file://artifacts/ecosort/public/trash/medicine_bottle.png"
type = "image"
title = "generated_image"

[[generated]]
id = "XFZaclhX7CvNK-sHlU9Y6"
uri = "file://artifacts/ecosort/public/trash/glass_jar.png"
type = "image"
title = "generated_image"

[[generated]]
id = "d_OBxEWZ8nJsa2OM0iEQ2"
uri = "file://artifacts/ecosort/public/trash/mustard_jar.png"
type = "image"
title = "generated_image"

[[generated]]
id = "VX2fNzW0fdEJ74QHh_OAB"
uri = "file://artifacts/ecosort/public/trash/glass_carafe.png"
type = "image"
title = "generated_image"

[[generated]]
id = "EteNxRUBgkIl-iq4AagtC"
uri = "file://artifacts/ecosort/public/trash/magazine.png"
type = "image"
title = "generated_image"

[[generated]]
id = "dCltbMt1YsyhI_yo6fc0k"
uri = "file://artifacts/ecosort/public/trash/paper_bag.png"
type = "image"
title = "generated_image"

[[generated]]
id = "XLNTzThGqSBKIHjhzxYkB"
uri = "file://artifacts/ecosort/public/trash/egg_carton.png"
type = "image"
title = "generated_image"

[[generated]]
id = "xWuNzMBnmGfuPrWLjDDkN"
uri = "file://artifacts/ecosort/public/trash/paper_roll.png"
type = "image"
title = "generated_image"

[[generated]]
id = "geshnu2OqOoKHgpc_xHyn"
uri = "file://artifacts/ecosort/public/trash/old_book.png"
type = "image"
title = "generated_image"

[[generated]]
id = "THjqVPsfjKzn1QtsZKa07"
uri = "file://artifacts/ecosort/public/trash/envelope.png"
type = "image"
title = "generated_image"

[[generated]]
id = "5FaW1nQB30Rb7dcxyFNUo"
uri = "file://artifacts/ecosort/public/trash/gift_paper.png"
type = "image"
title = "generated_image"

[[generated]]
id = "bMpezCdDbu1H1rhe-Zq4D"
uri = "file://artifacts/ecosort/public/trash/paper_napkin.png"
type = "image"
title = "generated_image"

[[generated]]
id = "uxyozF4dOa9IZTh2lafdQ"
uri = "file://artifacts/ecosort/public/trash/cereal_box.png"
type = "image"
title = "generated_image"

[[generated]]
id = "7kup-plTVMzSQajlnGEa8"
uri = "file://artifacts/ecosort/public/trash/shoebox.png"
type = "image"
title = "generated_image"

[[generated]]
id = "y5khEMNH7tpU7riOLz_hr"
uri = "file://artifacts/ecosort/public/trash/paper_sheet.png"
type = "image"
title = "generated_image"

[[generated]]
id = "XFfSZcCYflyc5J8kzJd2r"
uri = "file://artifacts/ecosort/public/trash/cardboard.png"
type = "image"
title = "generated_image"

[[generated]]
id = "A607LjtjvK4n_CaEWwSio"
uri = "file://artifacts/ecosort/public/trash/old_calendar.png"
type = "image"
title = "generated_image"

[[generated]]
id = "wGYYsvFuHm8aYx0nLrNxx"
uri = "file://artifacts/ecosort/public/trash/medicine_box.png"
type = "image"
title = "generated_image"

[[generated]]
id = "EFS24rEaAQoYac-cf6Iqf"
uri = "file://artifacts/ecosort/public/trash/paper_cup.png"
type = "image"
title = "generated_image"

[[generated]]
id = "qfJgKS8KMMKUSqqUuG8Rl"
uri = "file://artifacts/ecosort/public/trash/old_notebook.png"
type = "image"
title = "generated_image"

[[generated]]
id = "eyGC2v_gmRdx03FZuFc-0"
uri = "file://artifacts/ecosort/public/trash/cardboard_packaging.png"
type = "image"
title = "generated_image"

[[generated]]
id = "_lhI7fdtBHpGD8O1LIRJZ"
uri = "file://artifacts/ecosort/public/trash/plastic_plate.png"
type = "image"
title = "generated_image"

[[generated]]
id = "gWDjwL6TwcLb_qnxRMjin"
uri = "file://artifacts/ecosort/public/trash/plastic_cap.png"
type = "image"
title = "generated_image"

[[generated]]
id = "gM77aK1Ju8By9yvFcsHcT"
uri = "file://artifacts/ecosort/public/trash/ice_cream_container.png"
type = "image"
title = "generated_image"

[[generated]]
id = "g9KrGUheqBkL08eu96NgN"
uri = "file://artifacts/ecosort/public/trash/cling_wrap.png"
type = "image"
title = "generated_image"

[[generated]]
id = "SV4yXFpnlhBvbCdF64sY9"
uri = "file://artifacts/ecosort/public/trash/mustard_squeeze.png"
type = "image"
title = "generated_image"

[[generated]]
id = "3vtsts6pW-dWOyeZbkypa"
uri = "file://artifacts/ecosort/public/trash/small_water_bottle.png"
type = "image"
title = "generated_image"

[[generated]]
id = "dSaJOoT_j1RqtQU31XAwt"
uri = "file://artifacts/ecosort/public/trash/juice_tetrapak.png"
type = "image"
title = "generated_image"

[[generated]]
id = "56nzR1dE4HYMJZS3MRswJ"
uri = "file://artifacts/ecosort/public/trash/veggie_net.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Je0pUdKFKQsJ4jd39_Vsd"
uri = "file://artifacts/ecosort/public/trash/diaper.png"
type = "image"
title = "generated_image"

[[generated]]
id = "xba0Dt2f8rBVgQot4dW-p"
uri = "file://artifacts/ecosort/public/trash/chewing_gum.png"
type = "image"
title = "generated_image"

[[generated]]
id = "72b02kCrowpgKcEm649pK"
uri = "file://artifacts/ecosort/public/trash/used_bandage.png"
type = "image"
title = "generated_image"

[[generated]]
id = "dvXhEvdOOK20OLpbLbAZV"
uri = "file://artifacts/ecosort/public/trash/thermal_receipt.png"
type = "image"
title = "generated_image"

[[generated]]
id = "KtKFVILyXXpUSy6v_9MPU"
uri = "file://artifacts/ecosort/public/trash/razor_blade.png"
type = "image"
title = "generated_image"
