uploads = []
outputs = []

[[generated]]
id = "B3dxihr7OHqwQtWAkPeB_"
uri = "file://artifacts/ecosort/public/trash/oil_bottle.png"
type = "image"
title = "generated_image"

[[generated]]
id = "pRr8D2oDf58q-AMQoQ5Sa"
uri = "file://artifacts/ecosort/public/trash/sauce_jar.png"
type = "image"
title = "generated_image"

[[generated]]
id = "TXNZb_GZgsk22d3fo83FW"
uri = "file://artifacts/ecosort/public/trash/detergent_bottle.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ja1bhvy4KcRSp_I_g4ps_"
uri = "file://artifacts/ecosort/public/trash/plastic_fork.png"
type = "image"
title = "generated_image"

[[generated]]
id = "o4AX6HMQ3qT7P8I113T5n"
uri = "file://artifacts/ecosort/public/trash/tuna_can.png"
type = "image"
title = "generated_image"

[[generated]]
id = "fBTCMPoSe7MEJ7GNsSZDg"
uri = "file://artifacts/ecosort/public/trash/face_mask.png"
type = "image"
title = "generated_image"

[[generated]]
id = "OnjY0YR946pBfrWh3ZBlc"
uri = "file://artifacts/ecosort/public/trash/cotton_swab.png"
type = "image"
title = "generated_image"

[[generated]]
id = "-5GXs6wh6LY1QnBiVlRp4"
uri = "file://artifacts/ecosort/public/trash/broken_headphones.png"
type = "image"
title = "generated_image"

[[generated]]
id = "LMHyLQgR7U-vyyP8_n5WK"
uri = "file://artifacts/ecosort/public/trash/cd_disc.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Abz31ghjBJlAV4vMi5YbN"
uri = "file://artifacts/ecosort/public/trash/dead_aa_batteries.png"
type = "image"
title = "generated_image"

[[generated]]
id = "5u0sHvTSlXh1odwbCSFpZ"
uri = "file://artifacts/ecosort/public/trash/vinegar_bottle.png"
type = "image"
title = "generated_image"

[[generated]]
id = "e1gVhY-kwNAWgmjOeb_OP"
uri = "file://artifacts/ecosort/public/trash/mayo_jar.png"
type = "image"
title = "generated_image"

[[generated]]
id = "VgevguEHAaCtCF6cQGsJc"
uri = "file://artifacts/ecosort/public/trash/sparkling_bottle.png"
type = "image"
title = "generated_image"

[[generated]]
id = "cViaLGeNuhl9w1Yd9QUV4"
uri = "file://artifacts/ecosort/public/trash/plastic_container.png"
type = "image"
title = "generated_image"

[[generated]]
id = "4xoLHfw5ppF_1tsQ7GGXh"
uri = "file://artifacts/ecosort/public/trash/plastic_straw.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Vh3qC6e6aK9bzhU78eohw"
uri = "file://artifacts/ecosort/public/trash/vhs_cassette.png"
type = "image"
title = "generated_image"

[[generated]]
id = "QszV5oBST0avgFXxRZP0P"
uri = "file://artifacts/ecosort/public/trash/eraser.png"
type = "image"
title = "generated_image"

[[generated]]
id = "rlEkm5DBPwenlXZdxCSkQ"
uri = "file://artifacts/ecosort/public/trash/broken_keyboard.png"
type = "image"
title = "generated_image"

[[generated]]
id = "GGMev3bVRlMlmzAEFnC3N"
uri = "file://artifacts/ecosort/public/trash/broken_remote.png"
type = "image"
title = "generated_image"

[[generated]]
id = "CpGfWOCTVVOATWlwUKmQ8"
uri = "file://artifacts/ecosort/public/trash/fluorescent_bulb.png"
type = "image"
title = "generated_image"

[[generated]]
id = "wlp3Dm6OyY-uX5ebllfnc"
uri = "file://artifacts/ecosort/public/trash/pasta_leftovers.png"
type = "image"
title = "generated_image"

[[generated]]
id = "jatPPOqYSkrhZsxopb3P_"
uri = "file://artifacts/ecosort/public/trash/wilted_flowers.png"
type = "image"
title = "generated_image"

[[generated]]
id = "NZlGFPwrXW8x1NemVR2EG"
uri = "file://artifacts/ecosort/public/trash/kiwi_peel.png"
type = "image"
title = "generated_image"

[[generated]]
id = "5OUSMRPuDUSIlBjNrIYsM"
uri = "file://artifacts/ecosort/public/trash/vegetable_scraps.png"
type = "image"
title = "generated_image"

[[generated]]
id = "RYQcFk-JtOPhgaLh6Aq3I"
uri = "file://artifacts/ecosort/public/trash/pizza_crust.png"
type = "image"
title = "generated_image"

[[generated]]
id = "mwknKBJFusAZUa6N4YIxi"
uri = "file://artifacts/ecosort/public/trash/onion_peel.png"
type = "image"
title = "generated_image"

[[generated]]
id = "_Qy6UpbXXIC_Z445RkcmR"
uri = "file://artifacts/ecosort/public/trash/tomato_scraps.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Fqyq54jsLAgXFsKP3tXsL"
uri = "file://artifacts/ecosort/public/trash/dry_leaves.png"
type = "image"
title = "generated_image"

[[generated]]
id = "KGZmqbOtc8773nluSg7MN"
uri = "file://artifacts/ecosort/public/trash/cherry_pits.png"
type = "image"
title = "generated_image"

[[generated]]
id = "pRuryMvDexC7Oec85qjnv"
uri = "file://artifacts/ecosort/public/trash/rice_leftovers.png"
type = "image"
title = "generated_image"
