export type WasteCategory =
  | "Plastica"
  | "Carta"
  | "Vetro"
  | "Organico"
  | "Indifferenziato"
  | "RAEE";

export const wasteMapping: Record<string, WasteCategory> = {
  // --- PLASTICA ---
  "water bottle": "Plastica",
  "water jug": "Plastica",
  "pop bottle": "Plastica",
  "pill bottle": "Plastica",
  "plastic bag": "Plastica",
  "cup": "Plastica",
  "measuring cup": "Plastica",
  "bucket": "Plastica",
  "pail": "Plastica",
  "shopping basket": "Plastica",
  "tray": "Plastica",
  "tub": "Plastica",
  "can": "Plastica", // Spesso Alluminio va con Plastica/Vetro
  "tin can": "Plastica",
  "pop can": "Plastica",
  "soda can": "Plastica",
  "nipple": "Plastica",
  "pacifier": "Plastica",
  
  // --- CARTA ---
  "toilet tissue": "Carta",
  "envelope": "Carta",
  "carton": "Carta",
  "pizza box": "Carta",
  "notebook": "Carta",
  "book": "Carta",
  "comic book": "Carta",
  "book jacket": "Carta",
  "dust cover": "Carta",
  "binder": "Carta",
  "menu": "Carta",
  "crossword puzzle": "Carta",
  "jigsaw puzzle": "Carta",
  "file": "Carta",
  "folder": "Carta",
  "paper": "Carta",
  "newspaper": "Carta",
  "magazine": "Carta",
  "catalog": "Carta",
  "brochure": "Carta",
  "pamphlet": "Carta",

  // --- VETRO ---
  "beer bottle": "Vetro",
  "wine bottle": "Vetro",
  "beer glass": "Vetro",
  "goblet": "Vetro",
  "cocktail shaker": "Vetro",
  "pitcher": "Vetro",
  "carafe": "Vetro",
  "perfume": "Vetro",
  "essence": "Vetro",
  "beaker": "Vetro",

  // --- ORGANICO (Cibo) ---
  "banana": "Organico",
  "apple": "Organico",
  "orange": "Organico",
  "lemon": "Organico",
  "strawberry": "Organico",
  "pineapple": "Organico",
  "broccoli": "Organico",
  "cabbage": "Organico",
  "cauliflower": "Organico",
  "cucumber": "Organico",
  "mushroom": "Organico",
  "bell pepper": "Organico",
  "artichoke": "Organico",
  "corn": "Organico",
  "squash": "Organico",
  "zucchini": "Organico",
  "pumpkin": "Organico",
  "pomegranate": "Organico",
  "fig": "Organico",
  "grape": "Organico",
  "cherry": "Organico",
  "peach": "Organico",
  "pear": "Organico",
  "plum": "Organico",
  "tomato": "Organico",
  "potato": "Organico",
  "carrot": "Organico",
  "onion": "Organico",
  "garlic": "Organico",
  "hotdog": "Organico",
  "hamburger": "Organico",
  "cheeseburger": "Organico",
  "bagel": "Organico",
  "pretzel": "Organico",
  "bread": "Organico",
  "french loaf": "Organico",
  "ice cream": "Organico",
  "popsicle": "Organico",
  "doughnut": "Organico",
  "cake": "Organico",
  "cookie": "Organico",
  "chocolate": "Organico",
  "candy": "Organico",
  "sweet": "Organico",

  // --- RAEE (Elettronica) ---
  "mouse": "RAEE",
  "keyboard": "RAEE",
  "cellular telephone": "RAEE",
  "cellphone": "RAEE",
  "laptop": "RAEE",
  "monitor": "RAEE",
  "television": "RAEE",
  "tv": "RAEE",
  "remote control": "RAEE",
  "joystick": "RAEE",
  "joypad": "RAEE",
  "gamepad": "RAEE",
  "CD player": "RAEE",
  "radio": "RAEE",
  "battery": "RAEE",
  "calculator": "RAEE",
  "desktop computer": "RAEE",
  "hard disc": "RAEE",
  "hard drive": "RAEE",
  "modem": "RAEE",
  "printer": "RAEE",
  "speaker": "RAEE",
  "microphone": "RAEE",
  "ipod": "RAEE",
  "mp3 player": "RAEE",
  "toaster": "RAEE",
  "microwave": "RAEE",
  "oven": "RAEE",
  "vacuum": "RAEE",
  "vacuum cleaner": "RAEE",
  "iron": "RAEE",
  "hair dryer": "RAEE",
  "washer": "RAEE",
  "washing machine": "RAEE",
  "refrigerator": "RAEE",
  "fridge": "RAEE",
  "espresso maker": "RAEE",
  "coffee maker": "RAEE",
  "sewing machine": "RAEE",
  "typewriter": "RAEE",
  "electric fan": "RAEE",
  "space heater": "RAEE",
  "projector": "RAEE",
  "cash machine": "RAEE",

  // --- INDIFFERENZIATO ---
  "pen": "Indifferenziato",
  "pencil": "Indifferenziato",
  "lighter": "Indifferenziato",
  "toothbrush": "Indifferenziato",
  "diaper": "Indifferenziato",
  "sock": "Indifferenziato",
  "shirt": "Indifferenziato",
  "shoe": "Indifferenziato",
  "running shoe": "Indifferenziato",
  "sandal": "Indifferenziato",
  "boot": "Indifferenziato",
  "plate": "Indifferenziato",
  "coffee mug": "Indifferenziato",
  "mug": "Indifferenziato",
  "teapot": "Indifferenziato",
  "cd": "Indifferenziato",
  "dvd": "Indifferenziato",
  "sunglasses": "Indifferenziato",
  "umbrella": "Indifferenziato",
  "backpack": "Indifferenziato",
  "bag": "Indifferenziato",
  "wallet": "Indifferenziato",
  "purse": "Indifferenziato",
  "glove": "Indifferenziato",
  "hat": "Indifferenziato",
  "cap": "Indifferenziato",
  "helmet": "Indifferenziato",
  "mask": "Indifferenziato",
  "sponge": "Indifferenziato",
  "soap": "Indifferenziato",
  "lipstick": "Indifferenziato",
  "lotion": "Indifferenziato",
  "comb": "Indifferenziato",
  "brush": "Indifferenziato",
  "razor": "Indifferenziato",
  "bandage": "Indifferenziato",
  "band-aid": "Indifferenziato",
  "cotton": "Indifferenziato",
  "q-tip": "Indifferenziato",
  "paper towel": "Indifferenziato",
  "receipt": "Indifferenziato",
  "toilet seat": "Indifferenziato",
  "ashcan": "Indifferenziato",
  "trash can": "Indifferenziato",
  "garbage can": "Indifferenziato",
  "lighter": "Indifferenziato",
  "match": "Indifferenziato",
  "pacifier": "Indifferenziato",
  "lipstick": "Indifferenziato",
  "hair spray": "Indifferenziato",
  "perfume": "Vetro", // Profumo solitamente è in vetro
  "nail": "Indifferenziato",
  "screw": "Indifferenziato",
  "hammer": "Indifferenziato", // Metallo/Indifferenziato
  "screwdriver": "Indifferenziato",
  "wrench": "Indifferenziato",
  "ruler": "Indifferenziato",
  "eraser": "Indifferenziato",
  "rubber": "Indifferenziato",
  "scissor": "Indifferenziato",
  "tape": "Indifferenziato",
  "glue": "Indifferenziato",
};

export const wasteNotes: Record<string, string> = {
  "water bottle": "Ricordati di svuotarla completamente e schiacciarla prima di buttarla!",
  "pop bottle": "Ricordati di svuotarla completamente e schiacciarla prima di buttarla!",
  "can": "Schiacciala per ridurre il volume. Se è sporca, dalle una rapida sciacquata.",
  "tin can": "Schiacciala per ridurre il volume. Se è sporca, dalle una rapida sciacquata.",
  "pizza box": "Se è molto sporca di cibo, va nell'Organico (se compostabile) o Indifferenziato.",
  "battery": "Le pile esauste vanno negli appositi raccoglitori (spesso nei supermercati o centri raccolta), non nel normale bidone.",
  "receipt": "Gli scontrini termici non si possono riciclare, vanno sempre nell'Indifferenziato!",
  "paper towel": "Se è pulita va nella Carta, se è molto sporca di cibo o unta va nell'Indifferenziato o Organico (se compostabile).",
  "coffee mug": "La ceramica non va nel Vetro! Buttala nell'Indifferenziato o portala al centro di raccolta se molto voluminosa.",
  "mug": "La ceramica non va nel Vetro! Buttala nell'Indifferenziato o portala al centro di raccolta se molto voluminosa.",
  "plate": "Se è di ceramica o porcellana, non va nel Vetro! Va nell'Indifferenziato.",
  "diaper": "Pannolini e assorbenti vanno esclusivamente nell'Indifferenziato.",
  "toothpaste": "Il tubetto del dentifricio, se in plastica e vuoto, va nella Plastica.",
};

export const getWasteCategory = (predictions: { className: string, probability: number }[]): { category: WasteCategory, confidence: number, match: string, note?: string } | null => {
  if (!predictions || predictions.length === 0) return null;

  for (const pred of predictions) {
    const classes = pred.className.split(",").map(c => c.trim().toLowerCase());
    
    for (const c of classes) {
      if (wasteMapping[c]) {
        return {
          category: wasteMapping[c],
          confidence: pred.probability,
          match: c,
          note: wasteNotes[c]
        };
      }
    }
  }
  
  return null;
};
